# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
#
# orGit doesn't use the database, but we need to let rails connect to
# one so it doesn't complain
development:
  adapter: sqlite3
  database: db/orGit-db.sqlite3
  timeout: 5000

test:
  adapter: sqlite3
  database: db/orGit-db.sqlite3
  timeout: 5000

production:
  adapter: sqlite3
  database: db/orGit-db.sqlite3
  timeout: 5000
